[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
    Accept-Ranges = "bytes"

[[headers]]
  for = "/cpcl-intro.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
    Accept-Ranges = "bytes"

[[headers]]
  for = "*.webm"
  [headers.values]
    Content-Type = "video/webm"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.mov"
  [headers.values]
    Content-Type = "video/quicktime"
    Cache-Control = "public, max-age=31536000"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
